<a href="https://colab.research.google.com/github/ypg1um-arch/SAU_ML_TASKS/blob/main/Task_1A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1.Create arrays with NumPy
import numpy as np
a=np.array([5,6,9])#standard definition
print(a[0],a[1],a[2])#print the elements
print(a)#print the array
print('\n')
b=np.zeros((3,3))#zeros matrix
print(b)
print('\n')
c=np.ones((1,2))#ones matrix(1 row, 2 colums)[looks like a single row]
print(c)
print('\n')
d=np.ones((2,1))#[looks like a single column]
print(d)
print('\n')
e=np.arange(7)#arange from 0 to 6[input value 7]
print(e)
print('\n')
f=np.linspace(1,5,9)#9 numbers from 1 to 5 with interval=0.5[including 1 and 5]
print(f)
print('\n')

5 6 9
[5 6 9]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1.]]


[[1.]
 [1.]]


[0 1 2 3 4 5 6]


[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]




In [ ]:
# 2.Array indexing and slicing
import numpy as np
a = np.array([[6,7,6,9], [6,7,6,7], [6,9,6,9]])
b=a[1:,1:3]#(rows from 1 to 2, columns from 1 to 2)
print(a)
print('\n')
print(b)
print('\n')
b[0,0]=67#refers to first element of slice which is a[1,1]
print(a)#since b and a both look at same data, changing b changes a
print('\n')
a[1,1]=69#to confirm the above statement
print(b)
print('\n')
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))#integer idexing of 2d array
print('\n')
b = np.array([0, 2, 0, 1])#override b + choose your column
print(a[np.arange(1), b])#first row + choose columns in order
print('\n')
print(a[a > 7])#boolean indexing[print all elements greater than 7]
print('\n')

[[6 7 6 9]
 [6 7 6 7]
 [6 9 6 9]]


[[7 6]
 [9 6]]


[[ 6  7  6  9]
 [ 6 67  6  7]
 [ 6  9  6  9]]


[[69  6]
 [ 9  6]]


[ 6 69  6]


[6 6 6 7]


[ 9 69  9  9]




In [ ]:
# 3.Reshape and Transpose
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
r= a.reshape(2, 3)# Reshape into 2 rows and 3 columns
print(a)
print('\n')
print(r)
print('\n')
print(a.T)#Transpose of 1D matrix=same matrix
print('\n')
print(r.T)#Transpose of a 2D matrix

[1 2 3 4 5 6]


[[1 2 3]
 [4 5 6]]


[1 2 3 4 5 6]


[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# 4.Array Concatenation and Splitting
import numpy as np

a=np.array([1, 2, 3])
b=np.array([4, 5, 6])
c=np.concatenate((a,b))#standard syntax
print(c)
print('\n')
print(a+b)#this is sum, not concatenate
print('\n')
hw = 'Hello' + ' ' + 'World!'#we can simply concatenate with '+' for strings
print(hw)
print('\n')
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
c=np.concatenate((a,b),axis=0)#vertical stack
print(c)
print('\n')
c=np.concatenate((a,b),axis=1)#horizontal stack
print(c)#since 2d array, axis=1 means x axis and axis=0 means y axis
print('\n')
m = np.array([[10, 11, 12, 13],[20, 21, 22, 23],[30, 31, 32, 33],
                   [40, 41, 42, 43]])
l,r=np.vsplit(m, 2)#splits into top and bottom
print(l)
print('\n')
print(r)
print('\n')
l,r=np.hsplit(m, 2)#splits into right and left
print(l)
print('\n')
print(r)
print('\n')
l,l1,r,r1=np.vsplit(m, 4)#splits into rows
print(l)
print('\n')
print(r)
print('\n')
print(l1)
print('\n')
print(r1)
print('\n')
l,l1,r,r1=np.hsplit(m, 4)#splits into columns
print(l)
print('\n')
print(r)
print('\n')
print(l1)
print('\n')
print(r1)
print('\n')

[1 2 3 4 5 6]


[5 7 9]


Hello World!


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


[[10 11 12 13]
 [20 21 22 23]]


[[30 31 32 33]
 [40 41 42 43]]


[[10 11]
 [20 21]
 [30 31]
 [40 41]]


[[12 13]
 [22 23]
 [32 33]
 [42 43]]


[[10 11 12 13]]


[[30 31 32 33]]


[[20 21 22 23]]


[[40 41 42 43]]


[[10]
 [20]
 [30]
 [40]]


[[12]
 [22]
 [32]
 [42]]


[[11]
 [21]
 [31]
 [41]]


[[13]
 [23]
 [33]
 [43]]


