<a href="https://colab.research.google.com/github/ypg1um-arch/SAU_ML_TASKS/blob/main/Tasks_1B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# 1.Element-wise vs Matrix wise operations
#Element wise operations are mostly arithmetic
#Matrix wise operations are mainly matrix multiplication and Transpose
import numpy as np
x = np.array([[1,2],[3,4]], dtype=np.float64)#explicit type casting to float
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x + y)
print('\n')
print(np.add(x, y))#longer syntax
print('\n')
print(x - y)
print('\n')
print(np.subtract(x, y))#longer syntax
print('\n')
print(x * y)
print('\n')
print(np.multiply(x, y))#longer syntax
print('\n')
print(x / y)
print('\n')
print(np.divide(x, y))#longer syntax
print('\n')
print(np.sqrt(x))
print('\n')
print(np.sin(x))#input in radians
print('\n')
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.dot(a, b)#element wise multiplication
print(result)
print('\n')
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b))
print('\n')
v1 = np.array([1, 0, 0])#3D Vectors
v2 = np.array([0, 1, 0])
result = np.cross(v1, v2)#matrix multiplication[this is vector multiplication]
print(result)

[[ 6.  8.]
 [10. 12.]]


[[ 6.  8.]
 [10. 12.]]


[[-4. -4.]
 [-4. -4.]]


[[-4. -4.]
 [-4. -4.]]


[[ 5. 12.]
 [21. 32.]]


[[ 5. 12.]
 [21. 32.]]


[[0.2        0.33333333]
 [0.42857143 0.5       ]]


[[0.2        0.33333333]
 [0.42857143 0.5       ]]


[[1.         1.41421356]
 [1.73205081 2.        ]]


[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]


32


[[19 22]
 [43 50]]


[0 0 1]


In [5]:
#2.Statistical functions (mean, std, min, max)
import numpy as np
a = np.array([[1, 2, 3],[4, 5, 6]])
print(np.mean(a))          #All elements
print('\n')
print(np.mean(a, axis=0))  #y axis(down column)
print('\n')
print(np.mean(a, axis=1))  #x axis(across row)
print('\n')
print(np.std(a))           #Entire matrix
print('\n')
print(np.std(a, axis=0))   #Column-wise
print('\n')
print(np.std(a, axis=1))   #Row-wise
print('\n')
print(np.min(a, axis=0))   # Min of each column
print('\n')
print(np.max(a, axis=1))   # Max of each row
print('\n')

3.5


[2.5 3.5 4.5]


[2. 5.]


1.707825127659933


[1.5 1.5 1.5]


[0.81649658 0.81649658]


[1 2 3]


[3 6]




In [10]:
#3.Sorting and searching in arrays
#using built in numpy functions is better as they are highly optimised
import numpy as np
a = np.array([23, 14, 45, 86, 67, 9])
print(np.sort(a))#sorts in ascending order
print('\n')#for descending order, reverse the array
# although we can use descending=True in Numpy 2.0+ but this does not work here
a=np.array([[3, 1, 2],[6, 4, 5]])
print(np.sort(a, axis=1))
print(np.sort(a, axis=0))
print('\n')
prices = np.array([100, 20, 50])
items = np.array(["Shoes", "Socks", "Shirt"])

sorted_indices = np.argsort(prices) #indirect sort[used for data matching of 2 arrays]
print(sorted_indices)  # Output: [1 2 0] (Socks is cheapest, Shoes most expensive)
print('\n')
# Use indices to sort the items array
print(items[sorted_indices])  # Output: ['Socks' 'Shirt' 'Shoes']
print('\n')
sorted_a = np.array([10, 20, 30, 40, 50])
index = np.searchsorted(sorted_a, 25)#tells where 25 should go in array
print(index)
print('\n')

[ 9 14 23 45 67 86]


[[1 2 3]
 [4 5 6]]
[[3 1 2]
 [6 4 5]]


[1 2 0]


['Socks' 'Shirt' 'Shoes']


2




In [31]:
#4.Random number generation and seeding
#when you do seeding, the rng result is same everytime you run code
#rng is the random number generation object
import numpy as np
rng = np.random.default_rng(seed=1)#leave empty for new rng at every execution
print(rng.random(3))#prints 1d array
print('\n')
print(rng.random((2, 3)))#prints 2x3 array
print('\n')
rng1=np.random.default_rng()
print(rng1.random(3))#prints 1d array
print('\n')
print(rng1.random((2, 3)))#prints 2x3 array

[0.51182162 0.9504637  0.14415961]


[[0.94864945 0.31183145 0.42332645]
 [0.82770259 0.40919914 0.54959369]]


[0.76875633 0.04925948 0.87473178]


[[0.99174793 0.9222574  0.8773036 ]
 [0.34358458 0.13402438 0.40968578]]
